overrides: coala.yaml

name: corobo

dependencies:
  - pyopenssl
  - git+https://github.com/errbotio/errbot@a0f35732484c8c0692e123c48653517cffa21a42
  - wolframalpha
  - github3.py~=1.0.0
  - IGitt==0.4.1.dev20180317153318
  - gitpython
  - ramlient

configuration:
  template_dir:
    - .moban.dt/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: coala-gitignore.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: corobo-test-requirements.txt.jj2
